#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Mighty-Link AI Connect: Process Meeting Inputs Script (T609 - Meet/Gemini integration)
Author: Antigravity 2.0 (AI Agent)

This script parses a Meeting Minutes markdown file (generated by Meet/Gemini session,
e.g. docs/meetings/2026-06-02_CEO_Meeting_Minutes.md), automatically extracts:
1. The chosen service direction (A/B/C/D) and merges corresponding WBS Phase 7 tasks.
2. Unresolved action items (宿題/課題) and appends them to data/issues_tracker.tsv.
3. Newly raised questions/answers (質疑応答) and appends them to data/qa_tracker.tsv.

After parsing and merging, it automatically executes all Workspace Sync scripts
(Sheets, Calendar, Drive/NotebookLM docs) to establish a seamless Meeting-Driven Development loop.
"""

import os
import sys
import re
import csv
import subprocess
import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
DOCS_DIR = os.path.join(PROJECT_ROOT, "docs")
MEETINGS_DIR = os.path.join(DOCS_DIR, "meetings")

TSV_WBS = os.path.join(DATA_DIR, "WBS.tsv")
TSV_ISSUES = os.path.join(DATA_DIR, "issues_tracker.tsv")
TSV_QA = os.path.join(DATA_DIR, "qa_tracker.tsv")

DEFAULT_MEETING_MINUTES = os.path.join(MEETINGS_DIR, "2026-06-02_CEO_Meeting_Minutes.md")
SPREADSHEET_ID = "1L99HCBHr4IsVUWqnUuG6OgoUmxEQUdfaYQim1n6etB8"

def get_next_issue_id(filepath):
    """Finds the next sequential R-ID by scanning issues_tracker.tsv."""
    max_num = 27  # Default fallback based on existing R1-R27
    if os.path.exists(filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            reader = csv.reader(f, delimiter="\t")
            for row in reader:
                if row and row[0].startswith("R"):
                    try:
                        num = int(row[0][1:])
                        if num > max_num:
                            max_num = num
                    except ValueError:
                        pass
    return f"R{max_num + 1}"

def get_next_qa_id(filepath):
    """Finds the next sequential QA-ID by scanning qa_tracker.tsv."""
    max_num = 22  # Default fallback based on existing QA-01 to QA-22
    if os.path.exists(filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            reader = csv.reader(f, delimiter="\t")
            for row in reader:
                if row and row[0].startswith("QA-"):
                    try:
                        num = int(row[0][3:])
                        if num > max_num:
                            max_num = num
                    except ValueError:
                        pass
    return f"QA-{max_num + 1:02d}"

def parse_meeting_minutes(filepath):
    """Parses meeting minutes markdown and extracts WBS choice, issues, and QA."""
    if not os.path.exists(filepath):
        print(f"[-] Error: Meeting Minutes file not found at {filepath}")
        return None, [], []

    print(f"[*] Parsing Meeting Minutes: {os.path.relpath(filepath, PROJECT_ROOT)}")
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # 1. Parse service direction choice
    direction_choice = None
    dir_match = re.search(r"(?:決定されたサービス方向性|サービス方向性|方向性):\s*([A-Da-d])", content)
    if dir_match:
        direction_choice = dir_match.group(1).upper()
        print(f"[+] Detected service direction choice: {direction_choice}")
    else:
        print("[!] Warning: Could not detect service direction choice in the document.")

    # 2. Parse issues / action items
    issues = []
    # Seek sections like "## 保留事項・宿題"
    issues_section = re.search(r"##\s*(?:保留事項・宿題|宿題|課題|アクションアイテム).*?\n(.*?)(?=\n##|$)", content, re.DOTALL)
    if issues_section:
        lines = issues_section.group(1).strip().split("\n")
        for line in lines:
            # Matches unresolved checkbox issues: - [ ] [category][severity] Title ・ Impact ・ Mitigation (オーナー:Owner, WBS:TXXX, Docs:docs/X)
            # Highly resilient extraction
            if re.match(r"^\s*-\s*\[\s*[ ]\s*\]", line):
                pattern = r"-\s*\[\s*\]\s*\[(.*?)\]\s*\[(.*?)\]\s*(.*?)\s*・\s*(.*?)\s*・\s*(.*?)\s*\(オーナー:(.*?), WBS:(.*?), Docs:(.*?)\)"
                match = re.match(pattern, line)
                if match:
                    issues.append({
                        "category": match.group(1).strip(),
                        "severity": match.group(2).strip().upper(),
                        "title": match.group(3).strip(),
                        "impact": match.group(4).strip(),
                        "mitigation": match.group(5).strip(),
                        "owner": match.group(6).strip(),
                        "wbs": match.group(7).strip(),
                        "docs": match.group(8).strip()
                    })
                else:
                    # Fallback parser for simple manual entries
                    clean_line = re.sub(r"^\s*-\s*\[\s*[ ]\s*\]\s*", "", line).strip()
                    if clean_line:
                        issues.append({
                            "category": "adhoc-meet",
                            "severity": "MED",
                            "title": clean_line,
                            "impact": "Meet会議で挙がった宿題事項",
                            "mitigation": "担当者による後追い確認",
                            "owner": "人間",
                            "wbs": "",
                            "docs": ""
                        })

    # 3. Parse QA
    qa_list = []
    # Seek sections like "## 質疑応答" or "## Q&A"
    qa_section = re.search(r"##\s*(?:質疑応答|Q&A|想定QA).*?\n(.*?)(?=\n##|$)", content, re.DOTALL)
    if qa_section:
        text = qa_section.group(1).strip()
        # Find Q&A blocks
        q_matches = re.finditer(r"-\s*Q:\s*(.*?)\n-\s*A:\s*(.*?)(?=\n-\s*Q:|\n\n|$)", text, re.DOTALL)
        for m in q_matches:
            q_text = m.group(1).strip()
            a_block = m.group(2).strip()
            
            # Parse answer block details
            # E.g., [回答方針] ... [保留時の対応] ... [カテゴリ] ... [Docs] ...
            ans_match = re.search(r"\[回答方針\]\s*(.*?)\s*\[保留時の対応\]\s*(.*?)\s*\[カテゴリ\]\s*(.*?)\s*\[Docs\]\s*(.*)", a_block)
            if ans_match:
                qa_list.append({
                    "question": q_text,
                    "policy": ans_match.group(1).strip(),
                    "deferral": ans_match.group(2).strip(),
                    "category": ans_match.group(3).strip(),
                    "docs": ans_match.group(4).strip()
                })
            else:
                qa_list.append({
                    "question": q_text,
                    "policy": a_block,
                    "deferral": "特になし",
                    "category": "adhoc-qa",
                    "docs": ""
                })

    return direction_choice, issues, qa_list

def append_issues(issues):
    """Appends new issues safely to issues_tracker.tsv."""
    if not issues:
        return
    
    print(f"[*] Appending {len(issues)} new issues to issues_tracker.tsv...")
    today = datetime.date.today().isoformat()
    
    new_rows = []
    for issue in issues:
        next_id = get_next_issue_id(TSV_ISSUES)
        # Schema: ID, カテゴリ, 重要度, 状態, タイトル, 影響, 緩和策, オーナー, 起票日, 解決予定日, 関連 WBS, 関連 docs, 関連 Issue, メメモ, 更新日
        new_row = [
            next_id,
            issue["category"],
            issue["severity"],
            "open",
            issue["title"],
            issue["impact"],
            issue["mitigation"],
            issue["owner"],
            today,
            "",  # Target resolution date empty initially
            issue["wbs"],
            issue["docs"],
            "",  # Associated Github issue ID empty initially
            "Meet/Gemini議事録から自動起票",
            today
        ]
        new_rows.append(new_row)
        # Write to local cache so sequential IDs work
        with open(TSV_ISSUES, "a", encoding="utf-8", newline="") as f:
            writer = csv.writer(f, delimiter="\t")
            writer.writerow(new_row)
            
    print(f"[+] Appended successfully. Last ID generated: {next_id}")

def append_qa(qa_list):
    """Appends new QA pairs safely to qa_tracker.tsv."""
    if not qa_list:
        return
    
    print(f"[*] Appending {len(qa_list)} new QA pairs to qa_tracker.tsv...")
    today = datetime.date.today().isoformat()
    
    for qa in qa_list:
        next_id = get_next_qa_id(TSV_QA)
        # Schema: ID, カテゴリ, 質問, 回答方針, 保留時の対応, 関連論点, 関連 docs, 出典, 状態, 更新日
        new_row = [
            next_id,
            qa["category"],
            qa["question"],
            qa["policy"],
            qa["deferral"],
            "",  # Associated decision axis empty initially
            qa["docs"],
            "Meet 2026-06-02",
            "想定済",
            today
        ]
        with open(TSV_QA, "a", encoding="utf-8", newline="") as f:
            writer = csv.writer(f, delimiter="\t")
            writer.writerow(new_row)
            
    print(f"[+] Appended successfully. Last ID generated: {next_id}")

def run_sync_scripts():
    """Runs all WBS, calendar, and drive sync scripts to push updates to Workspace."""
    print("="*60)
    print("[*] Launching Workspace Sync Pipeline (Meeting-Driven Sync)...")
    print("="*60)
    
    # 1. Sheets Sync
    print("[*] Running sync_wbs_to_sheets.py...")
    subprocess.run([sys.executable, "scripts/sync_wbs_to_sheets.py", SPREADSHEET_ID], cwd=PROJECT_ROOT, check=True)
    
    # 2. Calendar Sync
    print("[*] Running sync_wbs_to_calendar.py...")
    subprocess.run([sys.executable, "scripts/sync_wbs_to_calendar.py"], cwd=PROJECT_ROOT, check=True)
    
    # 3. NotebookLM Docs to Drive
    print("[*] Running upload_notebooklm_docs_to_drive.py...")
    subprocess.run([sys.executable, "scripts/upload_notebooklm_docs_to_drive.py"], cwd=PROJECT_ROOT, check=True)
    
    print("="*60)
    print("[+] Workspace Sync Pipeline Executed Successfully!")
    print("="*60)

def main():
    print("="*60)
    print("[*] Mighty-Link AI Connect: Meeting/Gemini Input Processor")
    print("="*60)

    # 1. Determine input file
    input_file = DEFAULT_MEETING_MINUTES
    if len(sys.argv) > 1:
        input_file = sys.argv[1]
    
    if not os.path.exists(input_file):
        # Auto-create directory structure if needed
        os.makedirs(os.path.dirname(input_file), exist_ok=True)
        print(f"[-] Error: Input file '{input_file}' not found.")
        print(f"[*] Creating a mock template file at {input_file} for demonstration.")
        create_mock_template(input_file)
        print("[*] Please review the generated template, edit as needed, and re-run this script.")
        sys.exit(0)

    # 2. Parse Markdown
    choice, issues, qa_list = parse_meeting_minutes(input_file)

    # 3. Apply Decision WBS
    if choice:
        print(f"[*] Running apply_ceo_decisions.py with choice: {choice}...")
        subprocess.run([sys.executable, "scripts/apply_ceo_decisions.py", choice], cwd=PROJECT_ROOT, check=True)
    
    # 4. Append to trackers
    if issues:
        append_issues(issues)
    if qa_list:
        append_qa(qa_list)

    # 5. Pipeline triggers
    run_sync_scripts()
    
    print("[+] All processing complete. Workspace fully updated with Meet inputs.")
    print("="*60)

def create_mock_template(filepath):
    """Creates a mock CEO meeting minutes template file to demonstrate parsing."""
    template_content = """# 2026-06-02 社長打ち合わせ議事録 ( Meet & Gemini 実績 )

- 日時: 2026-06-02 15:00 - 16:00
- 参加者: 梅澤 啓 (CEO), 寛太梅澤, AIエージェント
- 決定されたサービス方向性: A

## 決定事項
1. サービス方向性は「A: AIフィット診断支援」とする。
2. 認証層はベーシック認証を最優先で導入する。

## 保留事項・宿題 (新規課題)
- [ ] [compliance][HIGH] 経歴書のマスキング法務合意確認 ・ 個人情報漏洩のリスク ・ 外部のコンプラ専門弁護士とNDA付きでリーガルレビューを行う (オーナー:人間+Claude, WBS:T710, Docs:docs/requirements.md)
- [ ] [cost][MED] APIコストの月額制限の検証 ・ 予算超過による実稼働停止リスク ・ Daily usage ledgersからGemini API制限閾値と通知フラグをテスト環境で調整する (オーナー:Codex, WBS:T707, Docs:docs/CEO_PRESENTATION_OPS_DISCUSSION_2026-06-02.md)

## 質疑応答 (新規QA)
- Q: 複数エンジニアのスキルgapを可視化する際、3人以上の同時比較は可能か？
- A: [回答方針] UIの視認性から最大5名までの横並び比較に対応する。[保留時の対応] 3人以上はタブ切り替え表示に切り替える。[カテゴリ] service-direction [Docs] docs/wireframes/README.md
- Q: AI診断の合格基準（スコアリング）のアルゴリズムは社長側で編集できるか？
- A: [回答方針] WBS管理スプレッドシート側に重み付け係数テーブルを設け、非エンジニアでも調整可能にする。[保留時の対応] 重み付けはデフォルト固定値とし、6/16以降に設定画面を作る。[カテゴリ] tech-ai [Docs] docs/requirements.md
"""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(template_content)
    print(f"[+] Created mock template at {filepath}")

if __name__ == "__main__":
    main()
