#!/usr/bin/env python3
"""Rotate local runtime logs for T748.

Firebase Hosting access logs live in Google Cloud Logging. This utility covers
repository-local logs generated by development, sync, audit, and CI helpers.
"""

from __future__ import annotations

import argparse
import gzip
import json
import shutil
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path


TASK_ID = "T748"
DEFAULT_PATTERNS = (
    "data/audit/*.jsonl",
    "data/external_api_usage*.jsonl",
    "logs/*.jsonl",
    "logs/*.log",
    "*.log",
)
DEFAULT_ARCHIVE_DIR = Path("data") / "log_archive"
DEFAULT_REPORT_PATH = Path("exports") / "log_rotation_report.json"
DEFAULT_MIN_AGE_DAYS = 7
DEFAULT_RETENTION_DAYS = 90
DEFAULT_MAX_BYTES = 10 * 1024 * 1024


@dataclass(frozen=True)
class RotationCandidate:
    source: str
    archive: str
    size_bytes: int
    age_days: float
    reason: str


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def assert_child_path(parent: Path, child: Path) -> None:
    parent_resolved = parent.resolve()
    child_resolved = child.resolve()
    if child_resolved == parent_resolved or parent_resolved not in child_resolved.parents:
        raise ValueError(f"Refusing to operate outside managed path: {child}")


def is_child_path(parent: Path, child: Path) -> bool:
    parent_resolved = parent.resolve()
    child_resolved = child.resolve()
    return child_resolved == parent_resolved or parent_resolved in child_resolved.parents


def archive_path_for(root: Path, archive_dir: Path, source: Path, now: datetime) -> Path:
    relative = source.resolve().relative_to(root.resolve()).as_posix().replace("/", "__")
    stamp = now.strftime("%Y%m%dT%H%M%SZ")
    return archive_dir / now.strftime("%Y") / now.strftime("%m") / f"{relative}.{stamp}.gz"


def collect_candidates(
    root: Path,
    archive_dir: Path,
    patterns: tuple[str, ...],
    min_age_days: int,
    max_bytes: int,
    now: datetime | None = None,
) -> list[RotationCandidate]:
    current = now or utc_now()
    root = root.resolve()
    archive_dir = archive_dir.resolve()
    candidates: dict[Path, RotationCandidate] = {}

    for pattern in patterns:
        for path in root.glob(pattern):
            if not path.is_file():
                continue
            source = path.resolve()
            if not is_child_path(root, source):
                continue
            if is_child_path(archive_dir, source) or source.suffix == ".gz":
                continue

            stat = source.stat()
            if stat.st_size <= 0:
                continue
            age_seconds = max(0.0, current.timestamp() - stat.st_mtime)
            age_days = age_seconds / 86400
            reasons: list[str] = []
            if age_days >= min_age_days:
                reasons.append(f"age>={min_age_days}d")
            if stat.st_size >= max_bytes:
                reasons.append(f"size>={max_bytes}b")
            if not reasons:
                continue

            archive = archive_path_for(root, archive_dir, source, current)
            candidates[source] = RotationCandidate(
                source=str(source.relative_to(root)),
                archive=str(archive.relative_to(root)),
                size_bytes=stat.st_size,
                age_days=round(age_days, 2),
                reason="+".join(reasons),
            )

    return [candidates[path] for path in sorted(candidates)]


def rotate_candidate(root: Path, archive_dir: Path, candidate: RotationCandidate) -> Path:
    source = (root / candidate.source).resolve()
    archive = (root / candidate.archive).resolve()
    assert_child_path(root, source)
    assert_child_path(archive_dir, archive)

    archive.parent.mkdir(parents=True, exist_ok=True)
    with source.open("rb") as src, gzip.open(archive, "wb") as dst:
        shutil.copyfileobj(src, dst)
    source.unlink()
    return archive


def prune_archives(
    root: Path,
    archive_dir: Path,
    retention_days: int,
    dry_run: bool,
    now: datetime | None = None,
) -> list[str]:
    if retention_days < 1:
        raise ValueError("retention-days must be >= 1")
    current = now or utc_now()
    archive_dir = archive_dir.resolve()
    pruned: list[str] = []
    if not archive_dir.exists():
        return pruned

    cutoff = current.timestamp() - (retention_days * 86400)
    for path in sorted(archive_dir.rglob("*.gz")):
        if not path.is_file():
            continue
        archive = path.resolve()
        assert_child_path(archive_dir, archive)
        if archive.stat().st_mtime <= cutoff:
            pruned.append(str(archive.relative_to(root.resolve())))
            if not dry_run:
                archive.unlink()
    return pruned


def write_report(report_path: Path, report: dict) -> None:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def display_path(root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path.resolve())


def build_report(
    *,
    dry_run: bool,
    root: Path,
    archive_dir: Path,
    patterns: tuple[str, ...],
    min_age_days: int,
    retention_days: int,
    max_bytes: int,
    candidates: list[RotationCandidate],
    rotated: list[str],
    pruned_archives: list[str],
) -> dict:
    return {
        "task_id": TASK_ID,
        "generated_at_utc": utc_now().isoformat(),
        "dry_run": dry_run,
        "root": ".",
        "archive_dir": display_path(root, archive_dir),
        "patterns": list(patterns),
        "min_age_days": min_age_days,
        "retention_days": retention_days,
        "max_bytes": max_bytes,
        "candidates": [asdict(candidate) for candidate in candidates],
        "rotated_archives": rotated,
        "pruned_archives": pruned_archives,
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compress, archive, and prune local runtime log files."
    )
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="Project root.")
    parser.add_argument(
        "--archive-dir",
        type=Path,
        default=DEFAULT_ARCHIVE_DIR,
        help="Archive directory, relative to root unless absolute.",
    )
    parser.add_argument(
        "--report-path",
        type=Path,
        default=DEFAULT_REPORT_PATH,
        help="JSON report path, relative to root unless absolute.",
    )
    parser.add_argument(
        "--pattern",
        action="append",
        default=None,
        help="Glob pattern relative to root. Repeat to override defaults.",
    )
    parser.add_argument("--min-age-days", type=int, default=DEFAULT_MIN_AGE_DAYS)
    parser.add_argument("--retention-days", type=int, default=DEFAULT_RETENTION_DAYS)
    parser.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = args.root.resolve()
    archive_dir = args.archive_dir if args.archive_dir.is_absolute() else root / args.archive_dir
    report_path = args.report_path if args.report_path.is_absolute() else root / args.report_path
    patterns = tuple(args.pattern or DEFAULT_PATTERNS)

    assert_child_path(root, archive_dir)
    assert_child_path(root, report_path)
    if args.min_age_days < 0:
        raise ValueError("min-age-days must be >= 0")
    if args.max_bytes < 1:
        raise ValueError("max-bytes must be >= 1")

    candidates = collect_candidates(
        root=root,
        archive_dir=archive_dir,
        patterns=patterns,
        min_age_days=args.min_age_days,
        max_bytes=args.max_bytes,
    )

    rotated: list[str] = []
    if not args.dry_run:
        for candidate in candidates:
            archive = rotate_candidate(root, archive_dir, candidate)
            rotated.append(str(archive.relative_to(root)))

    pruned_archives = prune_archives(
        root=root,
        archive_dir=archive_dir,
        retention_days=args.retention_days,
        dry_run=args.dry_run,
    )
    report = build_report(
        dry_run=args.dry_run,
        root=root,
        archive_dir=archive_dir,
        patterns=patterns,
        min_age_days=args.min_age_days,
        retention_days=args.retention_days,
        max_bytes=args.max_bytes,
        candidates=candidates,
        rotated=rotated,
        pruned_archives=pruned_archives,
    )
    write_report(report_path, report)

    action = "would rotate" if args.dry_run else "rotated"
    print(
        f"[+] T748 log rotation {action} {len(candidates)} file(s); "
        f"pruned {len(pruned_archives)} archive(s). Report: {report_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
