"""CEO meeting calendar evidence check (T911).

T988's re-audit (docs/PROJECT_STALL_REVIEW_2026-08-19.md) left T911 needing
"8/5会議の実施有無、決定事項、確認日を正本へ記録", and the WBS note warns that an
agenda entry must NOT be treated as proof of approval.

Whether a meeting happened, and what was decided, is a human fact. What CAN be
checked mechanically is whether the slot was ever secured on Google Calendar —
T911's own title includes 「予定確保」. This tool answers exactly that, and
nothing more.

For a given date it reports:

* events whose title looks like the CEO regular meeting (定例 / 社長定例),
* events overlapping the intended slot (a conflicting external meeting is
  evidence bearing on whether the slot was usable),
* events generated by scripts/sync_wbs_to_calendar.py, which are WBS tracker
  projections and are explicitly NOT meeting evidence.

Absence of an event is evidence, not proof — a meeting can be held ad hoc. The
tool therefore never concludes "not held"; it prints facts for a human, and its
exit code does not encode a verdict about the meeting.

Requires the project's Workspace OAuth (authorized_user.json) and network, so it
is registered in EXEMPT_GUARDS and is not run by the preflight.

Output: exports/ceo_meeting_calendar_evidence.{json,md}. No secrets are emitted.
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
AUTHORIZED_USER_FILE = PROJECT_ROOT / "authorized_user.json"
DEFAULT_JSON = PROJECT_ROOT / "exports" / "ceo_meeting_calendar_evidence.json"
DEFAULT_MD = PROJECT_ROOT / "exports" / "ceo_meeting_calendar_evidence.md"

# Titles that would indicate the CEO regular meeting itself.
MEETING_HINTS = ("社長定例", "定例")
# Events created by the WBS calendar sync - tracker projections, not evidence.
WBS_EVENT_PREFIX = "【Mighty Skill-Bridge】"


def _parse_iso(value: str) -> datetime.datetime | None:
    try:
        return datetime.datetime.fromisoformat(value)
    except (TypeError, ValueError):
        return None


def overlaps(start: str, end: str, slot_start: str, slot_end: str) -> bool:
    """True when [start,end) overlaps the intended slot.

    All-day entries carry a date rather than a timestamp and are not treated as
    occupying a specific time slot.
    """
    s, e = _parse_iso(start), _parse_iso(end)
    ss, se = _parse_iso(slot_start), _parse_iso(slot_end)
    if not (s and e and ss and se):
        return False
    # All-day entries ("2026-08-05") parse to naive datetimes. They do not occupy
    # a specific time slot, and comparing them with the tz-aware slot raises
    # TypeError, so treat them as non-overlapping rather than crashing.
    if any(d.tzinfo is None for d in (s, e, ss, se)):
        return False
    return s < se and ss < e


def classify_event(summary: str) -> str:
    """wbs_tracker / candidate_meeting / other."""
    if summary.startswith(WBS_EVENT_PREFIX):
        return "wbs_tracker"
    if any(hint in summary for hint in MEETING_HINTS):
        return "candidate_meeting"
    return "other"


def _service():
    from google.oauth2.credentials import Credentials as UserCredentials
    from googleapiclient.discovery import build

    info = json.loads(AUTHORIZED_USER_FILE.read_text(encoding="utf-8"))
    creds = UserCredentials.from_authorized_user_info(info)
    return build("calendar", "v3", credentials=creds, cache_discovery=False)


def collect(date: str, slot_start: str, slot_end: str) -> dict[str, Any]:
    svc = _service()
    cals = svc.calendarList().list(maxResults=50).execute().get("items", [])
    day_start = f"{date}T00:00:00+09:00"
    day_end = f"{date}T23:59:59+09:00"

    events: list[dict[str, Any]] = []
    for cal in cals:
        try:
            items = svc.events().list(
                calendarId=cal["id"], timeMin=day_start, timeMax=day_end,
                singleEvents=True, orderBy="startTime", maxResults=100,
            ).execute().get("items", [])
        except Exception:
            continue
        for ev in items:
            start = ev.get("start", {})
            end = ev.get("end", {})
            s = start.get("dateTime") or start.get("date", "")
            e = end.get("dateTime") or end.get("date", "")
            summary = ev.get("summary", "")
            events.append({
                "calendar": cal.get("summary", ""),
                "start": s,
                "end": e,
                "all_day": "dateTime" not in start,
                "summary": summary,
                "kind": classify_event(summary),
                "overlaps_slot": overlaps(s, e, slot_start, slot_end),
            })

    meetings = [e for e in events if e["kind"] == "candidate_meeting"]
    trackers = [e for e in events if e["kind"] == "wbs_tracker"]
    conflicts = [e for e in events if e["overlaps_slot"] and e["kind"] != "wbs_tracker"]
    return {
        "date": date,
        "slot": {"start": slot_start, "end": slot_end},
        "calendars_checked": [c.get("summary", "") for c in cals],
        "events": events,
        "candidate_meetings": meetings,
        "wbs_tracker_events": trackers,
        "slot_conflicts": conflicts,
        "slot_secured": bool(meetings),
    }


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# 社長定例 実施証跡（カレンダー照会） (T911)",
        "",
        f"- 対象日: **{report['date']}** / 想定枠: {report['slot']['start']} - {report['slot']['end']}",
        f"- 照会カレンダー: {len(report['calendars_checked'])}件 "
        f"({', '.join(report['calendars_checked'])})",
        f"- 定例らしきイベント: **{len(report['candidate_meetings'])}件**",
        f"- 想定枠と重複する予定: **{len(report['slot_conflicts'])}件**",
        "",
        "> カレンダー不在は不開催の**証拠**であって**証明ではない**。"
        "実施有無の確定は人間が行う。",
        "",
        "| カレンダー | 開始 | 終了 | 件名 | 区分 | 枠重複 |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for e in report["events"]:
        mark = "YES" if e["overlaps_slot"] else ""
        lines.append(
            f"| {e['calendar'][:24]} | {e['start']} | {e['end']} | {e['summary'][:44]} "
            f"| {e['kind']} | {mark} |"
        )
    lines += [
        "",
        "※ `wbs_tracker` は sync_wbs_to_calendar.py が WBS 行から生成したタスク管理"
        "イベントであり、会議の実施証跡ではない。",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="社長定例のカレンダー実施証跡照会 (T911)")
    parser.add_argument("--date", default="2026-08-05")
    parser.add_argument("--slot-start", default=None, help="既定: <date>T13:30:00+09:00")
    parser.add_argument("--slot-end", default=None, help="既定: <date>T14:30:00+09:00")
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--md", type=Path, default=DEFAULT_MD)
    args = parser.parse_args(argv)

    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8", errors="replace")

    slot_start = args.slot_start or f"{args.date}T13:30:00+09:00"
    slot_end = args.slot_end or f"{args.date}T14:30:00+09:00"

    if not AUTHORIZED_USER_FILE.exists():
        print("[-] authorized_user.json が見つかりません（Workspace認証が必要）")
        return 2
    try:
        report = collect(args.date, slot_start, slot_end)
    except Exception as exc:  # network / auth failure
        print(f"[-] カレンダー照会に失敗しました: {type(exc).__name__}: {exc}")
        print("[*] 本ツールはネットワークとWorkspace認証を必要とします（プリフライト対象外）。")
        return 2

    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    md = render_markdown(report)
    args.md.write_text(md, encoding="utf-8")
    print(md)
    # 事実の提示のみを行い、実施有無を終了コードで断定しない
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
