"""Bidirectional sales email matching service for T817_5.

The module consumes the sanitized extraction review generated by T817_4 and
builds project-to-talent and talent-to-project candidate lists. It never reads
or writes raw email bodies.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Sequence


DEFAULT_EXTRACTION_REPORT = Path("exports") / "sales_email_extraction_review.json"
DEFAULT_JSON_REPORT = Path("exports") / "sales_email_match_review.json"
DEFAULT_MARKDOWN_REPORT = Path("exports") / "sales_email_match_review.md"
MATCH_MODEL_NAME = "deterministic-sales-email-matcher-v1"
REQUIRED_PRIVACY_CONTROLS = {
    "raw_email_body_not_written",
    "email_phone_secret_patterns_redacted_from_evidence",
    "talent_identity_anonymized",
}


@dataclass(frozen=True)
class SearchCriteria:
    direction: str = "project_to_talent"
    skills: tuple[str, ...] = ()
    remote: str = ""
    min_score: int = 0
    limit: int = 20
    project_key: str = ""
    talent_key: str = ""


@dataclass(frozen=True)
class ProjectRecord:
    project_key: str
    title: str
    required_skills: list[str]
    nice_to_have_skills: list[str]
    skill_categories: dict[str, list[str]]
    rate_min: int | None
    rate_max: int | None
    location: str
    remote_type: str
    start_date_text: str
    evidence_excerpt: str
    confidence: float
    source_paths: list[str]


@dataclass(frozen=True)
class TalentRecord:
    talent_key: str
    display_name: str
    skills: list[str]
    skill_categories: dict[str, list[str]]
    desired_rate_min: int | None
    desired_rate_max: int | None
    desired_location: str
    remote_preference: str
    availability_text: str
    evidence_excerpt: str
    confidence: float
    source_paths: list[str]


def utc_timestamp() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def as_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def as_dict(value: Any) -> dict[str, list[str]]:
    if not isinstance(value, dict):
        return {}
    normalized: dict[str, list[str]] = {}
    for key, values in value.items():
        normalized[str(key)] = as_list(values)
    return normalized


def compact_text(value: Any, max_chars: int = 220) -> str:
    text = " ".join(str(value or "").split())
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 1].rstrip() + "…"


def skill_key(value: str) -> str:
    return value.strip().casefold()


def skill_union(*groups: Iterable[str]) -> set[str]:
    values: set[str] = set()
    for group in groups:
        values.update(skill_key(item) for item in group if str(item).strip())
    return values


def confidence_value(value: Any) -> float:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return 0.5
    return max(0.0, min(numeric, 1.0))


def stable_key(*parts: object) -> str:
    joined = "|".join(str(part or "").strip().casefold() for part in parts)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()


def load_extraction_report(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {
            "task_id": "T817_4",
            "generated_at": utc_timestamp(),
            "privacy_controls": [],
            "extractions": [],
        }
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Extraction report must be a JSON object: {path}")
    return data


def validate_privacy_controls(report: dict[str, Any]) -> list[str]:
    controls = set(as_list(report.get("privacy_controls")))
    missing = sorted(REQUIRED_PRIVACY_CONTROLS - controls)
    if missing:
        raise ValueError("Extraction report is missing privacy controls: " + ", ".join(missing))
    return sorted(controls)


def project_from_item(item: dict[str, Any]) -> ProjectRecord | None:
    project = item.get("project_requirement")
    if not isinstance(project, dict):
        return None
    required = as_list(project.get("required_skills"))
    nice = as_list(project.get("nice_to_have_skills"))
    if not required and not nice:
        return None
    key = stable_key(project.get("title"), ",".join(sorted(required)), project.get("rate_min"), project.get("remote_type"))
    return ProjectRecord(
        project_key="project_" + key[:16],
        title=compact_text(project.get("title") or item.get("normalized_subject") or "Untitled project", 120),
        required_skills=sorted(set(required), key=str.casefold),
        nice_to_have_skills=sorted(set(nice), key=str.casefold),
        skill_categories=as_dict(project.get("skill_categories")),
        rate_min=project.get("rate_min") if isinstance(project.get("rate_min"), int) else None,
        rate_max=project.get("rate_max") if isinstance(project.get("rate_max"), int) else None,
        location=compact_text(project.get("location"), 80),
        remote_type=compact_text(project.get("remote_type"), 40) or "unknown",
        start_date_text=compact_text(project.get("start_date_text"), 80),
        evidence_excerpt=compact_text(project.get("evidence_excerpt"), 240),
        confidence=confidence_value(project.get("confidence")),
        source_paths=[str(item.get("source_path") or "")],
    )


def talent_from_item(item: dict[str, Any]) -> TalentRecord | None:
    talent = item.get("talent_profile")
    if not isinstance(talent, dict):
        return None
    skills = as_list(talent.get("skills"))
    if not skills:
        return None
    key = compact_text(talent.get("anonymized_talent_key"), 80)
    return TalentRecord(
        talent_key=key or ("talent_" + stable_key(item.get("dedupe_key"))[:16]),
        display_name=key or "匿名候補者",
        skills=sorted(set(skills), key=str.casefold),
        skill_categories=as_dict(talent.get("skill_categories")),
        desired_rate_min=talent.get("desired_rate_min") if isinstance(talent.get("desired_rate_min"), int) else None,
        desired_rate_max=talent.get("desired_rate_max") if isinstance(talent.get("desired_rate_max"), int) else None,
        desired_location=compact_text(talent.get("desired_location"), 80),
        remote_preference=compact_text(talent.get("remote_preference"), 40) or "unknown",
        availability_text=compact_text(talent.get("availability_text"), 80),
        evidence_excerpt=compact_text(talent.get("evidence_excerpt"), 240),
        confidence=confidence_value(talent.get("confidence")),
        source_paths=[str(item.get("source_path") or "")],
    )


def merge_projects(projects: Sequence[ProjectRecord]) -> list[ProjectRecord]:
    merged: dict[str, ProjectRecord] = {}
    for project in projects:
        existing = merged.get(project.project_key)
        if existing is None:
            merged[project.project_key] = project
            continue
        merged[project.project_key] = ProjectRecord(
            **{
                **asdict(existing),
                "source_paths": sorted(set(existing.source_paths + project.source_paths)),
                "confidence": max(existing.confidence, project.confidence),
            }
        )
    return sorted(merged.values(), key=lambda item: item.title.casefold())


def merge_talents(talents: Sequence[TalentRecord]) -> list[TalentRecord]:
    merged: dict[str, TalentRecord] = {}
    for talent in talents:
        existing = merged.get(talent.talent_key)
        if existing is None:
            merged[talent.talent_key] = talent
            continue
        merged[talent.talent_key] = TalentRecord(
            **{
                **asdict(existing),
                "skills": sorted(set(existing.skills + talent.skills), key=str.casefold),
                "source_paths": sorted(set(existing.source_paths + talent.source_paths)),
                "confidence": max(existing.confidence, talent.confidence),
            }
        )
    return sorted(merged.values(), key=lambda item: item.display_name.casefold())


def project_records(report: dict[str, Any]) -> list[ProjectRecord]:
    return merge_projects(
        [
            record
            for item in report.get("extractions", [])
            if isinstance(item, dict)
            for record in [project_from_item(item)]
            if record is not None
        ]
    )


def talent_records(report: dict[str, Any]) -> list[TalentRecord]:
    return merge_talents(
        [
            record
            for item in report.get("extractions", [])
            if isinstance(item, dict)
            for record in [talent_from_item(item)]
            if record is not None
        ]
    )


def condition_fit(project: ProjectRecord, talent: TalentRecord) -> tuple[float, list[str], list[str]]:
    points = 0.0
    total = 0.0
    matched: list[str] = []
    gaps: list[str] = []

    if project.remote_type and project.remote_type != "unknown":
        total += 1.0
        if talent.remote_preference in {project.remote_type, "remote"} or project.remote_type == "remote":
            points += 1.0
            matched.append(f"remote:{project.remote_type}")
        else:
            gaps.append(f"remote mismatch: project={project.remote_type}, talent={talent.remote_preference}")

    if project.location:
        total += 1.0
        if not talent.desired_location or talent.desired_location == "unknown" or project.location == talent.desired_location:
            points += 0.7
            matched.append(f"location:{project.location}")
        else:
            gaps.append(f"location check: project={project.location}, talent={talent.desired_location}")

    if project.rate_min or project.rate_max:
        total += 1.0
        if talent.desired_rate_min is None and talent.desired_rate_max is None:
            points += 0.5
            gaps.append("rate needs review")
        else:
            project_ceiling = project.rate_max or project.rate_min or 0
            talent_floor = talent_desired_min_or_zero(talent)
            if project_ceiling >= talent_floor:
                points += 1.0
                matched.append("rate compatible")
            else:
                gaps.append("rate below talent preference")

    if total == 0:
        return 0.55, matched, gaps
    return points / total, matched, gaps


def talent_desired_min_or_zero(talent: TalentRecord) -> int:
    return talent.desired_rate_min or talent.desired_rate_max or 0


def score_pair(project: ProjectRecord, talent: TalentRecord) -> dict[str, Any]:
    talent_skills = skill_union(talent.skills)
    required_keys = skill_union(project.required_skills)
    nice_keys = skill_union(project.nice_to_have_skills)
    display_by_key = {skill_key(skill): skill for skill in talent.skills + project.required_skills + project.nice_to_have_skills}

    matched_required_keys = sorted(required_keys & talent_skills)
    matched_nice_keys = sorted(nice_keys & talent_skills)
    missing_required_keys = sorted(required_keys - talent_skills)

    required_ratio = len(matched_required_keys) / len(required_keys) if required_keys else 0.55
    nice_ratio = len(matched_nice_keys) / len(nice_keys) if nice_keys else 0.5
    condition_ratio, matched_conditions, condition_gaps = condition_fit(project, talent)
    confidence_ratio = (project.confidence + talent.confidence) / 2

    score = round(
        100
        * (
            (required_ratio * 0.58)
            + (nice_ratio * 0.12)
            + (condition_ratio * 0.20)
            + (confidence_ratio * 0.10)
        )
    )
    score = max(0, min(score, 100))
    missing_skills = [display_by_key.get(key, key) for key in missing_required_keys]
    matched_skills = [display_by_key.get(key, key) for key in sorted(set(matched_required_keys + matched_nice_keys))]

    mismatch_reasons = list(condition_gaps)
    if missing_skills:
        mismatch_reasons.insert(0, "missing required skills: " + ", ".join(missing_skills[:6]))
    if not mismatch_reasons:
        mismatch_reasons.append("major mismatches not detected in sanitized fields")

    reason_parts = []
    if matched_skills:
        reason_parts.append("skill overlap: " + ", ".join(matched_skills[:6]))
    if matched_conditions:
        reason_parts.append("conditions: " + ", ".join(matched_conditions[:4]))
    if not reason_parts:
        reason_parts.append("review sanitized evidence before outreach")

    return {
        "project_key": project.project_key,
        "project_title": project.title,
        "talent_key": talent.talent_key,
        "talent_label": talent.display_name,
        "score": score,
        "score_breakdown": {
            "required_skill_fit": round(required_ratio * 100),
            "nice_skill_fit": round(nice_ratio * 100),
            "condition_fit": round(condition_ratio * 100),
            "evidence_confidence": round(confidence_ratio * 100),
        },
        "matched_skills": matched_skills,
        "missing_skills": missing_skills,
        "matched_conditions": matched_conditions,
        "mismatch_reasons": mismatch_reasons,
        "match_reason": "; ".join(reason_parts),
        "project_evidence": project.evidence_excerpt,
        "talent_evidence": talent.evidence_excerpt,
        "review_status": "pending",
    }


def criteria_from_values(
    *,
    direction: str = "project_to_talent",
    skills: Sequence[str] | str = (),
    remote: str = "",
    min_score: int = 0,
    limit: int = 20,
    project_key: str = "",
    talent_key: str = "",
) -> SearchCriteria:
    if isinstance(skills, str):
        skill_values = tuple(item.strip() for item in skills.split(",") if item.strip())
    else:
        skill_values = tuple(str(item).strip() for item in skills if str(item).strip())
    normalized_direction = direction if direction in {"project_to_talent", "talent_to_project"} else "project_to_talent"
    return SearchCriteria(
        direction=normalized_direction,
        skills=skill_values,
        remote=remote.strip(),
        min_score=max(0, min(int(min_score or 0), 100)),
        limit=max(1, min(int(limit or 20), 100)),
        project_key=project_key.strip(),
        talent_key=talent_key.strip(),
    )


def match_satisfies(match: dict[str, Any], project: ProjectRecord, talent: TalentRecord, criteria: SearchCriteria) -> bool:
    if match["score"] < criteria.min_score:
        return False
    if criteria.project_key and project.project_key != criteria.project_key:
        return False
    if criteria.talent_key and talent.talent_key != criteria.talent_key:
        return False
    if criteria.remote:
        remote_key = criteria.remote.casefold()
        if remote_key not in {project.remote_type.casefold(), talent.remote_preference.casefold()}:
            return False
    if criteria.skills:
        combined = skill_union(project.required_skills, project.nice_to_have_skills, talent.skills)
        wanted = {skill_key(item) for item in criteria.skills}
        if not wanted.issubset(combined):
            return False
    return True


def build_match_report(report: dict[str, Any], criteria: SearchCriteria | None = None) -> dict[str, Any]:
    criteria = criteria or SearchCriteria()
    controls = validate_privacy_controls(report)
    projects = project_records(report)
    talents = talent_records(report)

    match_rows: list[dict[str, Any]] = []
    for project in projects:
        for talent in talents:
            match = score_pair(project, talent)
            if match_satisfies(match, project, talent, criteria):
                match_rows.append(match)

    match_rows.sort(key=lambda item: (-int(item["score"]), str(item["project_title"]), str(item["talent_label"])))
    limited_matches = match_rows[: criteria.limit]
    if criteria.direction == "talent_to_project":
        limited_matches = sorted(
            limited_matches,
            key=lambda item: (str(item["talent_label"]), -int(item["score"]), str(item["project_title"])),
        )

    return {
        "task_id": "T817_5",
        "generated_at": utc_timestamp(),
        "model_name": MATCH_MODEL_NAME,
        "direction": criteria.direction,
        "filters": asdict(criteria),
        "privacy_controls": controls + [
            "raw_email_body_not_loaded",
            "match_output_uses_redacted_evidence_only",
            "human_review_required_before_outreach",
        ],
        "project_count": len(projects),
        "talent_count": len(talents),
        "match_count": len(limited_matches),
        "projects": [asdict(project) for project in projects],
        "talents": [asdict(talent) for talent in talents],
        "matches": limited_matches,
    }


def build_match_report_from_file(path: Path, criteria: SearchCriteria | None = None) -> dict[str, Any]:
    return build_match_report(load_extraction_report(path), criteria)


def write_json_report(report: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def write_markdown_report(report: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Sales Email Match Review\n",
        "\n",
        f"- Task: {report.get('task_id')}\n",
        f"- Generated at: {report.get('generated_at')}\n",
        f"- Direction: {report.get('direction')}\n",
        f"- Projects: {report.get('project_count')}\n",
        f"- Talents: {report.get('talent_count')}\n",
        f"- Matches: {report.get('match_count')}\n",
        "- Privacy: only sanitized extraction fields and redacted evidence are used.\n",
        "\n",
        "| # | Project | Talent | Score | Matched skills | Missing skills | Reason | Review |\n",
        "| --- | --- | --- | --- | --- | --- | --- | --- |\n",
    ]
    for index, item in enumerate(report.get("matches", []), start=1):
        if not isinstance(item, dict):
            continue
        lines.append(
            "| {index} | {project} | {talent} | {score}% | {matched} | {missing} | {reason} | {review} |\n".format(
                index=index,
                project=str(item.get("project_title", "")).replace("|", "\\|"),
                talent=str(item.get("talent_label", "")).replace("|", "\\|"),
                score=item.get("score", ""),
                matched=", ".join(as_list(item.get("matched_skills"))).replace("|", "\\|"),
                missing=", ".join(as_list(item.get("missing_skills"))).replace("|", "\\|"),
                reason=str(item.get("match_reason", "")).replace("|", "\\|"),
                review=str(item.get("review_status", "")).replace("|", "\\|"),
            )
        )
    path.write_text("".join(lines), encoding="utf-8", newline="\n")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build bidirectional sales email matching candidates for T817_5.")
    parser.add_argument("--input-report", default=str(DEFAULT_EXTRACTION_REPORT))
    parser.add_argument("--json-report", default=str(DEFAULT_JSON_REPORT))
    parser.add_argument("--markdown-report", default=str(DEFAULT_MARKDOWN_REPORT))
    parser.add_argument("--direction", choices=["project_to_talent", "talent_to_project"], default="project_to_talent")
    parser.add_argument("--skills", default="", help="Comma-separated skill filters.")
    parser.add_argument("--remote", default="")
    parser.add_argument("--min-score", type=int, default=0)
    parser.add_argument("--limit", type=int, default=20)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    criteria = criteria_from_values(
        direction=args.direction,
        skills=args.skills,
        remote=args.remote,
        min_score=args.min_score,
        limit=args.limit,
    )
    report = build_match_report_from_file(Path(args.input_report), criteria)
    write_json_report(report, Path(args.json_report))
    write_markdown_report(report, Path(args.markdown_report))
    print(
        "Built {match_count} matches from {project_count} projects and {talent_count} talents".format(
            match_count=report["match_count"],
            project_count=report["project_count"],
            talent_count=report["talent_count"],
        )
    )
    print(f"Wrote {args.json_report} and {args.markdown_report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
