"""Bidirectional sales email matching service for T817_5.

The module consumes the sanitized extraction review generated by T817_4 and
builds project-to-talent and talent-to-project candidate lists. It never reads
or writes raw email bodies.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from datetime import date, datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path
from typing import Any, Iterable, Sequence
from zoneinfo import ZoneInfo


DEFAULT_EXTRACTION_REPORT = Path("exports") / "sales_email_extraction_review.json"
DEFAULT_JSON_REPORT = Path("exports") / "sales_email_match_review.json"
DEFAULT_MARKDOWN_REPORT = Path("exports") / "sales_email_match_review.md"
MATCH_MODEL_NAME = "deterministic-sales-email-matcher-v1"
JST = ZoneInfo("Asia/Tokyo")
REQUIRED_PRIVACY_CONTROLS = {
    "raw_email_body_not_written",
    "email_phone_secret_patterns_redacted_from_evidence",
    "talent_identity_anonymized",
}


@dataclass(frozen=True)
class SearchCriteria:
    direction: str = "project_to_talent"
    skills: tuple[str, ...] = ()
    remote: str = ""
    contract_type: str = ""
    min_score: int = 0
    limit: int = 20
    project_key: str = ""
    talent_key: str = ""
    min_rate: int | None = None
    max_rate: int | None = None
    search_query: str = ""
    received_from: str = ""
    received_to: str = ""


@dataclass(frozen=True)
class ProjectRecord:
    project_key: str
    title: str
    required_skills: list[str]
    nice_to_have_skills: list[str]
    skill_categories: dict[str, list[str]]
    rate_min: int | None
    rate_max: int | None
    location: str
    remote_type: str
    contract_type: str
    start_date_text: str
    evidence_excerpt: str
    confidence: float
    sender_domains: list[str]
    source_paths: list[str]
    received_at: str
    received_date: str


@dataclass(frozen=True)
class TalentRecord:
    talent_key: str
    display_name: str
    skills: list[str]
    skill_categories: dict[str, list[str]]
    desired_rate_min: int | None
    desired_rate_max: int | None
    desired_location: str
    remote_preference: str
    contract_type: str
    availability_text: str
    evidence_excerpt: str
    confidence: float
    sender_domains: list[str]
    source_paths: list[str]
    received_at: str
    received_date: str


def utc_timestamp() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def as_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def as_dict(value: Any) -> dict[str, list[str]]:
    if not isinstance(value, dict):
        return {}
    normalized: dict[str, list[str]] = {}
    for key, values in value.items():
        normalized[str(key)] = as_list(values)
    return normalized


def compact_text(value: Any, max_chars: int = 220) -> str:
    text = " ".join(str(value or "").split())
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 1].rstrip() + "…"


def normalize_received_timestamp(value: Any) -> tuple[str, str]:
    """Normalize RFC 2822 or ISO timestamps to a JST timestamp and date."""
    raw_value = compact_text(value, 160)
    if not raw_value:
        return "", ""

    parsed: datetime | None = None
    try:
        parsed = datetime.fromisoformat(raw_value.replace("Z", "+00:00"))
    except ValueError:
        try:
            parsed = parsedate_to_datetime(raw_value)
        except (TypeError, ValueError):
            return "", ""

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=JST)
    local_received_at = parsed.astimezone(JST).replace(microsecond=0)
    return local_received_at.isoformat(), local_received_at.date().isoformat()


SKILL_SYNONYMS: dict[str, str] = {
    "react.js": "react",
    "reactjs": "react",
    "vue.js": "vue",
    "vuejs": "vue",
    "node.js": "node",
    "nodejs": "node",
    "ts": "typescript",
    "js": "javascript",
    "py": "python",
    "postgres": "postgresql",
    "postgres sql": "postgresql",
    "postgresql": "postgresql",
    "k8s": "kubernetes",
    "gcp": "google cloud",
    "aws cloud": "aws",
    "c sharp": "c#",
    "csharp": "c#",
    "golang": "go",
}


def skill_key(value: str) -> str:
    cleaned = value.strip().casefold()
    return SKILL_SYNONYMS.get(cleaned, cleaned)


def detect_contract_type(text: str) -> str:
    cleaned = str(text or "").casefold()
    if any(k in cleaned for k in ["準委任", "ses", "委任", "準委任契約"]):
        return "準委任"
    if any(k in cleaned for k in ["派遣", "特定派遣", "一般派遣"]):
        return "派遣"
    if any(k in cleaned for k in ["請負", "受託", "一括請負", "成果物"]):
        return "請負"
    if any(k in cleaned for k in ["正社員", "契約社員", "直接雇用"]):
        return "正社員/契約社員"
    return "準委任"


def skill_union(*groups: Iterable[str]) -> set[str]:
    values: set[str] = set()
    for group in groups:
        values.update(skill_key(item) for item in group if str(item).strip())
    return values


def confidence_value(value: Any) -> float:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return 0.5
    return max(0.0, min(numeric, 1.0))


def stable_key(*parts: object) -> str:
    joined = "|".join(str(part or "").strip().casefold() for part in parts)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()


def load_extraction_report(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {
            "task_id": "T817_4",
            "generated_at": utc_timestamp(),
            "privacy_controls": [],
            "extractions": [],
        }
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Extraction report must be a JSON object: {path}")
    return data


def validate_privacy_controls(report: dict[str, Any]) -> list[str]:
    controls = set(as_list(report.get("privacy_controls")))
    missing = sorted(REQUIRED_PRIVACY_CONTROLS - controls)
    if missing:
        raise ValueError("Extraction report is missing privacy controls: " + ", ".join(missing))
    return sorted(controls)


def project_from_item(item: dict[str, Any]) -> ProjectRecord | None:
    project = item.get("project_requirement")
    if not isinstance(project, dict):
        return None
    required = as_list(project.get("required_skills"))
    nice = as_list(project.get("nice_to_have_skills"))
    if not required and not nice:
        return None
    received_at, received_date = normalize_received_timestamp(item.get("received_at"))
    sender_domain_value = compact_text(item.get("sender_domain"), 120)
    key = stable_key(project.get("title"), ",".join(sorted(required)), project.get("rate_min"), project.get("remote_type"))
    evidence = compact_text(project.get("evidence_excerpt"), 240)
    contract = project.get("contract_type") or detect_contract_type(f"{project.get('title')} {evidence}")
    return ProjectRecord(
        project_key="project_" + key[:16],
        title=compact_text(project.get("title") or item.get("normalized_subject") or "Untitled project", 120),
        required_skills=sorted(set(required), key=str.casefold),
        nice_to_have_skills=sorted(set(nice), key=str.casefold),
        skill_categories=as_dict(project.get("skill_categories")),
        rate_min=project.get("rate_min") if isinstance(project.get("rate_min"), int) else None,
        rate_max=project.get("rate_max") if isinstance(project.get("rate_max"), int) else None,
        location=compact_text(project.get("location"), 80),
        remote_type=compact_text(project.get("remote_type"), 40) or "unknown",
        contract_type=compact_text(contract, 40),
        start_date_text=compact_text(project.get("start_date_text"), 80),
        evidence_excerpt=evidence,
        confidence=confidence_value(project.get("confidence")),
        sender_domains=[sender_domain_value] if sender_domain_value else [],
        source_paths=[str(item.get("source_path") or "")],
        received_at=received_at,
        received_date=received_date,
    )


def talent_from_item(item: dict[str, Any]) -> TalentRecord | None:
    talent = item.get("talent_profile")
    if not isinstance(talent, dict):
        return None
    skills = as_list(talent.get("skills"))
    if not skills:
        return None
    received_at, received_date = normalize_received_timestamp(item.get("received_at"))
    sender_domain_value = compact_text(item.get("sender_domain"), 120)
    key = compact_text(talent.get("anonymized_talent_key"), 80)
    evidence = compact_text(talent.get("evidence_excerpt"), 240)
    contract = talent.get("contract_type") or detect_contract_type(evidence)
    return TalentRecord(
        talent_key=key or ("talent_" + stable_key(item.get("dedupe_key"))[:16]),
        display_name=key or "匿名候補者",
        skills=sorted(set(skills), key=str.casefold),
        skill_categories=as_dict(talent.get("skill_categories")),
        desired_rate_min=talent.get("desired_rate_min") if isinstance(talent.get("desired_rate_min"), int) else None,
        desired_rate_max=talent.get("desired_rate_max") if isinstance(talent.get("desired_rate_max"), int) else None,
        desired_location=compact_text(talent.get("desired_location"), 80),
        remote_preference=compact_text(talent.get("remote_preference"), 40) or "unknown",
        contract_type=compact_text(contract, 40),
        availability_text=compact_text(talent.get("availability_text"), 80),
        evidence_excerpt=evidence,
        confidence=confidence_value(talent.get("confidence")),
        sender_domains=[sender_domain_value] if sender_domain_value else [],
        source_paths=[str(item.get("source_path") or "")],
        received_at=received_at,
        received_date=received_date,
    )


def merge_projects(projects: Sequence[ProjectRecord]) -> list[ProjectRecord]:
    merged: dict[str, ProjectRecord] = {}
    for project in projects:
        existing = merged.get(project.project_key)
        if existing is None:
            merged[project.project_key] = project
            continue
        merged[project.project_key] = ProjectRecord(
            **{
                **asdict(existing),
                "sender_domains": sorted(set(existing.sender_domains + project.sender_domains)),
                "source_paths": sorted(set(existing.source_paths + project.source_paths)),
                "confidence": max(existing.confidence, project.confidence),
                "received_at": max(existing.received_at, project.received_at),
                "received_date": max(existing.received_date, project.received_date),
            }
        )
    return sorted(merged.values(), key=lambda item: item.title.casefold())


def merge_talents(talents: Sequence[TalentRecord]) -> list[TalentRecord]:
    merged: dict[str, TalentRecord] = {}
    for talent in talents:
        existing = merged.get(talent.talent_key)
        if existing is None:
            merged[talent.talent_key] = talent
            continue
        merged[talent.talent_key] = TalentRecord(
            **{
                **asdict(existing),
                "skills": sorted(set(existing.skills + talent.skills), key=str.casefold),
                "sender_domains": sorted(set(existing.sender_domains + talent.sender_domains)),
                "source_paths": sorted(set(existing.source_paths + talent.source_paths)),
                "confidence": max(existing.confidence, talent.confidence),
                "received_at": max(existing.received_at, talent.received_at),
                "received_date": max(existing.received_date, talent.received_date),
            }
        )
    return sorted(merged.values(), key=lambda item: item.display_name.casefold())


def project_records(report: dict[str, Any]) -> list[ProjectRecord]:
    return merge_projects(
        [
            record
            for item in report.get("extractions", [])
            if isinstance(item, dict)
            for record in [project_from_item(item)]
            if record is not None
        ]
    )


def talent_records(report: dict[str, Any]) -> list[TalentRecord]:
    return merge_talents(
        [
            record
            for item in report.get("extractions", [])
            if isinstance(item, dict)
            for record in [talent_from_item(item)]
            if record is not None
        ]
    )


def condition_fit(project: ProjectRecord, talent: TalentRecord) -> tuple[float, list[str], list[str]]:
    points = 0.0
    total = 0.0
    matched: list[str] = []
    gaps: list[str] = []

    if project.remote_type and project.remote_type != "unknown":
        total += 1.0
        if talent.remote_preference in {project.remote_type, "remote"} or project.remote_type == "remote":
            points += 1.0
            matched.append(f"remote:{project.remote_type}")
        else:
            gaps.append(f"remote mismatch: project={project.remote_type}, talent={talent.remote_preference}")

    if project.location:
        total += 1.0
        if not talent.desired_location or talent.desired_location == "unknown" or project.location == talent.desired_location:
            points += 0.7
            matched.append(f"location:{project.location}")
        else:
            gaps.append(f"location check: project={project.location}, talent={talent.desired_location}")

    if project.rate_min or project.rate_max:
        total += 1.0
        if talent.desired_rate_min is None and talent.desired_rate_max is None:
            points += 0.5
            gaps.append("rate needs review")
        else:
            project_ceiling = project.rate_max or project.rate_min or 0
            talent_floor = talent_desired_min_or_zero(talent)
            if project_ceiling >= talent_floor:
                points += 1.0
                matched.append("rate compatible")
            else:
                gaps.append("rate below talent preference")

    if total == 0:
        return 0.55, matched, gaps
    return points / total, matched, gaps


def talent_desired_min_or_zero(talent: TalentRecord) -> int:
    return talent.desired_rate_min or talent.desired_rate_max or 0


def score_pair(project: ProjectRecord, talent: TalentRecord) -> dict[str, Any]:
    talent_skills = skill_union(talent.skills)
    required_keys = skill_union(project.required_skills)
    nice_keys = skill_union(project.nice_to_have_skills)
    display_by_key = {skill_key(skill): skill for skill in talent.skills + project.required_skills + project.nice_to_have_skills}

    matched_required_keys = sorted(required_keys & talent_skills)
    matched_nice_keys = sorted(nice_keys & talent_skills)
    missing_required_keys = sorted(required_keys - talent_skills)

    required_ratio = len(matched_required_keys) / len(required_keys) if required_keys else 0.55
    nice_ratio = len(matched_nice_keys) / len(nice_keys) if nice_keys else 0.5
    condition_ratio, matched_conditions, condition_gaps = condition_fit(project, talent)
    confidence_ratio = (project.confidence + talent.confidence) / 2

    score = round(
        100
        * (
            (required_ratio * 0.58)
            + (nice_ratio * 0.12)
            + (condition_ratio * 0.20)
            + (confidence_ratio * 0.10)
        )
    )
    score = max(0, min(score, 100))
    missing_skills = [display_by_key.get(key, key) for key in missing_required_keys]
    matched_skills = [display_by_key.get(key, key) for key in sorted(set(matched_required_keys + matched_nice_keys))]

    mismatch_reasons = list(condition_gaps)
    if missing_skills:
        mismatch_reasons.insert(0, "missing required skills: " + ", ".join(missing_skills[:6]))
    if not mismatch_reasons:
        mismatch_reasons.append("major mismatches not detected in sanitized fields")

    reason_parts = []
    if matched_skills:
        reason_parts.append("skill overlap: " + ", ".join(matched_skills[:6]))
    if matched_conditions:
        reason_parts.append("conditions: " + ", ".join(matched_conditions[:4]))
    if not reason_parts:
        reason_parts.append("review sanitized evidence before outreach")

    return {
        "project_key": project.project_key,
        "project_title": project.title,
        "project_received_at": project.received_at,
        "project_received_date": project.received_date,
        "talent_key": talent.talent_key,
        "talent_label": talent.display_name,
        "talent_received_at": talent.received_at,
        "talent_received_date": talent.received_date,
        "score": score,
        "score_breakdown": {
            "required_skill_fit": round(required_ratio * 100),
            "nice_skill_fit": round(nice_ratio * 100),
            "condition_fit": round(condition_ratio * 100),
            "evidence_confidence": round(confidence_ratio * 100),
        },
        "matched_skills": matched_skills,
        "missing_skills": missing_skills,
        "matched_conditions": matched_conditions,
        "mismatch_reasons": mismatch_reasons,
        "match_reason": "; ".join(reason_parts),
        "project_evidence": project.evidence_excerpt,
        "talent_evidence": talent.evidence_excerpt,
        "review_status": "pending",
    }


def parse_optional_rate(name: str, value: int | str | None) -> int | None:
    if value is None or str(value).strip() == "":
        return None
    try:
        parsed = int(str(value).strip())
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be a non-negative integer") from exc
    if parsed < 0:
        raise ValueError(f"{name} must be a non-negative integer")
    return parsed


def parse_optional_date(name: str, value: str | None) -> str:
    normalized = str(value or "").strip()
    if not normalized:
        return ""
    try:
        return date.fromisoformat(normalized).isoformat()
    except ValueError as exc:
        raise ValueError(f"{name} must be a valid YYYY-MM-DD date") from exc


def criteria_from_values(
    *,
    direction: str = "project_to_talent",
    skills: Sequence[str] | str = (),
    remote: str = "",
    contract_type: str = "",
    min_score: int = 0,
    limit: int = 20,
    project_key: str = "",
    talent_key: str = "",
    min_rate: int | str | None = None,
    max_rate: int | str | None = None,
    search_query: str = "",
    received_from: str = "",
    received_to: str = "",
) -> SearchCriteria:
    if isinstance(skills, str):
        skill_values = tuple(item.strip() for item in skills.split(",") if item.strip())
    else:
        skill_values = tuple(str(item).strip() for item in skills if str(item).strip())
    normalized_direction = direction if direction in {"project_to_talent", "talent_to_project"} else "project_to_talent"
    parsed_min_rate = parse_optional_rate("min_rate", min_rate)
    parsed_max_rate = parse_optional_rate("max_rate", max_rate)
    if parsed_min_rate is not None and parsed_max_rate is not None and parsed_min_rate > parsed_max_rate:
        raise ValueError("min_rate must not exceed max_rate")
    parsed_received_from = parse_optional_date("received_from", received_from)
    parsed_received_to = parse_optional_date("received_to", received_to)
    if parsed_received_from and parsed_received_to and parsed_received_from > parsed_received_to:
        raise ValueError("received_from must not exceed received_to")

    return SearchCriteria(
        direction=normalized_direction,
        skills=skill_values,
        remote=remote.strip(),
        contract_type=contract_type.strip(),
        min_score=max(0, min(int(min_score or 0), 100)),
        limit=max(1, min(int(limit or 20), 100)),
        project_key=project_key.strip(),
        talent_key=talent_key.strip(),
        min_rate=parsed_min_rate,
        max_rate=parsed_max_rate,
        search_query=search_query.strip().casefold(),
        received_from=parsed_received_from,
        received_to=parsed_received_to,
    )


def rate_range_overlaps(project: ProjectRecord, min_rate: int | None, max_rate: int | None) -> bool:
    if min_rate is None and max_rate is None:
        return True
    if project.rate_min is None and project.rate_max is None:
        return False

    project_floor = project.rate_min if project.rate_min is not None else project.rate_max
    project_ceiling = project.rate_max if project.rate_max is not None else project.rate_min
    assert project_floor is not None and project_ceiling is not None
    project_floor, project_ceiling = sorted((project_floor, project_ceiling))

    if min_rate is not None and project_ceiling < min_rate:
        return False
    if max_rate is not None and project_floor > max_rate:
        return False
    return True


def match_satisfies(match: dict[str, Any], project: ProjectRecord, talent: TalentRecord, criteria: SearchCriteria) -> bool:
    if match["score"] < criteria.min_score:
        return False
    if criteria.project_key and project.project_key != criteria.project_key:
        return False
    if criteria.talent_key and talent.talent_key != criteria.talent_key:
        return False
    if criteria.remote:
        remote_key = criteria.remote.casefold()
        if remote_key not in {project.remote_type.casefold(), talent.remote_preference.casefold()}:
            return False
    if criteria.contract_type:
        c_want = criteria.contract_type.casefold()
        p_c = project.contract_type.casefold()
        t_c = talent.contract_type.casefold()
        if c_want not in {p_c, t_c}:
            return False
    if criteria.skills:
        combined = skill_union(project.required_skills, project.nice_to_have_skills, talent.skills)
        wanted = {skill_key(item) for item in criteria.skills}
        if not wanted.issubset(combined):
            return False
    if not rate_range_overlaps(project, criteria.min_rate, criteria.max_rate):
        return False
    if criteria.received_from or criteria.received_to:
        if not project.received_date:
            return False
        if criteria.received_from and project.received_date < criteria.received_from:
            return False
        if criteria.received_to and project.received_date > criteria.received_to:
            return False
    if criteria.search_query:
        query = criteria.search_query
        searchable_text = " ".join(
            [
                project.title,
                talent.display_name,
                *project.required_skills,
                *project.nice_to_have_skills,
                *talent.skills,
                *project.sender_domains,
                *talent.sender_domains,
                project.location,
                project.remote_type,
                talent.desired_location,
                talent.remote_preference,
                project.evidence_excerpt,
                talent.evidence_excerpt,
            ]
        ).casefold()
        if query not in searchable_text:
            return False
    return True


def build_match_report(report: dict[str, Any], criteria: SearchCriteria | None = None) -> dict[str, Any]:
    criteria = criteria or SearchCriteria()
    controls = validate_privacy_controls(report)
    projects = project_records(report)
    talents = talent_records(report)

    match_rows: list[dict[str, Any]] = []
    for project in projects:
        for talent in talents:
            match = score_pair(project, talent)
            if match_satisfies(match, project, talent, criteria):
                match_rows.append(match)

    match_rows.sort(key=lambda item: (-int(item["score"]), str(item["project_title"]), str(item["talent_label"])))
    limited_matches = match_rows[: criteria.limit]
    if criteria.direction == "talent_to_project":
        limited_matches = sorted(
            limited_matches,
            key=lambda item: (str(item["talent_label"]), -int(item["score"]), str(item["project_title"])),
        )

    referenced_project_keys = {str(item["project_key"]) for item in limited_matches}
    referenced_talent_keys = {str(item["talent_key"]) for item in limited_matches}
    response_projects = [project for project in projects if project.project_key in referenced_project_keys]
    response_talents = [talent for talent in talents if talent.talent_key in referenced_talent_keys]

    return {
        "task_id": "T817_5",
        "generated_at": utc_timestamp(),
        "model_name": MATCH_MODEL_NAME,
        "direction": criteria.direction,
        "filters": asdict(criteria),
        "privacy_controls": controls + [
            "raw_email_body_not_loaded",
            "match_output_uses_redacted_evidence_only",
            "human_review_required_before_outreach",
        ],
        "project_count": len(projects),
        "talent_count": len(talents),
        "match_count": len(limited_matches),
        "projects": [asdict(project) for project in response_projects],
        "talents": [asdict(talent) for talent in response_talents],
        "matches": limited_matches,
    }


def build_match_report_from_file(path: Path, criteria: SearchCriteria | None = None) -> dict[str, Any]:
    return build_match_report(load_extraction_report(path), criteria)


def write_json_report(report: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def write_markdown_report(report: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Sales Email Match Review\n",
        "\n",
        f"- Task: {report.get('task_id')}\n",
        f"- Generated at: {report.get('generated_at')}\n",
        f"- Direction: {report.get('direction')}\n",
        f"- Projects: {report.get('project_count')}\n",
        f"- Talents: {report.get('talent_count')}\n",
        f"- Matches: {report.get('match_count')}\n",
        "- Privacy: only sanitized extraction fields and redacted evidence are used.\n",
        "\n",
        "| # | Project | Talent | Score | Matched skills | Missing skills | Reason | Review |\n",
        "| --- | --- | --- | --- | --- | --- | --- | --- |\n",
    ]
    for index, item in enumerate(report.get("matches", []), start=1):
        if not isinstance(item, dict):
            continue
        lines.append(
            "| {index} | {project} | {talent} | {score}% | {matched} | {missing} | {reason} | {review} |\n".format(
                index=index,
                project=str(item.get("project_title", "")).replace("|", "\\|"),
                talent=str(item.get("talent_label", "")).replace("|", "\\|"),
                score=item.get("score", ""),
                matched=", ".join(as_list(item.get("matched_skills"))).replace("|", "\\|"),
                missing=", ".join(as_list(item.get("missing_skills"))).replace("|", "\\|"),
                reason=str(item.get("match_reason", "")).replace("|", "\\|"),
                review=str(item.get("review_status", "")).replace("|", "\\|"),
            )
        )
    path.write_text("".join(lines), encoding="utf-8", newline="\n")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build bidirectional sales email matching candidates for T817_5.")
    parser.add_argument("--input-report", default=str(DEFAULT_EXTRACTION_REPORT))
    parser.add_argument("--json-report", default=str(DEFAULT_JSON_REPORT))
    parser.add_argument("--markdown-report", default=str(DEFAULT_MARKDOWN_REPORT))
    parser.add_argument("--direction", choices=["project_to_talent", "talent_to_project"], default="project_to_talent")
    parser.add_argument("--skills", default="", help="Comma-separated skill filters.")
    parser.add_argument("--remote", default="")
    parser.add_argument("--min-score", type=int, default=0)
    parser.add_argument("--min-rate", type=int)
    parser.add_argument("--max-rate", type=int)
    parser.add_argument("--search-query", default="")
    parser.add_argument("--received-from", default="", help="Project email received date lower bound (YYYY-MM-DD).")
    parser.add_argument("--received-to", default="", help="Project email received date upper bound (YYYY-MM-DD).")
    parser.add_argument("--limit", type=int, default=20)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    criteria = criteria_from_values(
        direction=args.direction,
        skills=args.skills,
        remote=args.remote,
        min_score=args.min_score,
        min_rate=args.min_rate,
        max_rate=args.max_rate,
        search_query=args.search_query,
        received_from=args.received_from,
        received_to=args.received_to,
        limit=args.limit,
    )
    report = build_match_report_from_file(Path(args.input_report), criteria)
    write_json_report(report, Path(args.json_report))
    write_markdown_report(report, Path(args.markdown_report))
    print(
        "Built {match_count} matches from {project_count} projects and {talent_count} talents".format(
            match_count=report["match_count"],
            project_count=report["project_count"],
            talent_count=report["talent_count"],
        )
    )
    print(f"Wrote {args.json_report} and {args.markdown_report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
